### ISSUE TITLE
systemctl needs to have a path

### ISSUE THREAD

**Issue by threepistons** [derdanne/puppet-nfs#101]
In my agent runs I get:

> Failed to apply catalog: Validation of Exec[systemctl daemon-reload] failed: 'systemctl daemon-reload' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppetlabs/code/environments/pidev/modules/nfs/manifests/client/config.pp:56

https://github.com/derdanne/puppet-nfs/blob/4db2627bdeec773bae36576151e399054786302d/manifests/client/config.pp#L56 indeed needs to either say `/bin/systemctl daemon-reload` or have a path parameter.

**Comment by derdanne** [comment]
Hi, 

thanks for the report! This is correct, i will fix this in the next release.
