### ISSUE TITLE
nfs-kernel-server.service appears "stopped"

### ISSUE THREAD

**Issue by stephenkenny** [derdanne/puppet-nfs#103]
I've noticed recently that the Puppet agent running on our NFS server nodes seems to think that `nfs-kernel-server.service` is not running, even though it is.  We're seeing this output from the agent each time it runs:

`Notice: /Stage[main]/Nfs_server_exports/Service[nfs-kernel-server.service]/ensure: ensure changed 'stopped' to 'running' (corrective)
Info: /Stage[main]/Nfs_server_exports/Service[nfs-kernel-server.service]: Unscheduling refresh on Service[nfs-kernel-server.service]`

It doesn't look like anything actually happens though (there's no service restart as far as I can see).  I should say that this is also happening on our machines with a different, unrelated service.  So maybe it's not specific to the puppet-nfs module.   We are running Puppet Server 6.3.0, Puppet agent 6.4.0, on Debian 9.9.  

This isn't a big problem, just thought it might be worth reporting.

**Comment by derdanne** [comment]
Hey, thanks for the report. 

Can you please add an info about the used version of this module?

**Comment by stephenkenny** [comment]
Yes, sorry - we're using derdanne-nfs v2.1.2. 

(Our Puppet server version is 6.3.0, the agent version is 6.4.2;  both are running on Debian 9.9).

**Comment by derdanne** [comment]
Sorry, i could not reproduce this behaviour. Please reopen, when this issue is directly related to this module.
