### ISSUE TITLE
nfs::functions::create_export does not create directory on puppet 5.5.16

### ISSUE THREAD

**Issue by h-haaks** [derdanne/puppet-nfs#107]
Seems like the switch from 'if ! defined(File[$name]) {' to 'unless File[$name] {' in https://github.com/derdanne/puppet-nfs/commit/8642188242dfce6a6c29263c9579e4ffcaf6ea15#diff-e0decee37a1f161cb206745fe3eaaf12 is causing it.

Could you please change this back and release a new version to forge?

Regards 
Hugo

**Comment by runejuhl** [comment]
That seems to be a bug:

```puppet
file { '/tmp/omglol':
  ensure => 'file',
}

if defined(File['/tmp/omglol']) {
  notify { 'file is defined': }
}

$b = File['/tmp/omglol2']

if $b {
  notify { "this is not true: ${b}": }
}

if defined($b) {
  notify { "this is not defined true: ${b}": }
}
```

This results in the following:

~~~
Notice: Compiled catalog for managua.lan in environment production in 0.03 seconds
Notice: file is defined
Notice: /Stage[main]/Main/Notify[file is defined]/message: defined 'message' as 'file is defined'
Notice: this is not true: File['/tmp/omglol2']
Notice: /Stage[main]/Main/Notify[this is not true: File['/tmp/omglol2']]/message: defined 'message' as 'this is not true: File[\'/tmp/omglol2\']'
Notice: Applied catalog in 0.02 seconds
~~~

I.e. `File['/whatever']` will always be true, while `defined(File['/whatever'])` will only be true if the resource actually is defined.
