### ISSUE TITLE
Could not find init script or upstart conf file for 'nfs-lock'

### ISSUE THREAD

**Issue by bissa** [derdanne/puppet-nfs#11]
Got this on Ubuntu 14.04 with puppet 4.2.0

Debug: Service[nfs-lock](provider=upstart): Could not find nfs-lock.conf in /etc/init
Debug: Service[nfs-lock](provider=upstart): Could not find nfs-lock.conf in /etc/init.d
Debug: Service[nfs-lock](provider=upstart): Could not find nfs-lock in /etc/init
Debug: Service[nfs-lock](provider=upstart): Could not find nfs-lock in /etc/init.d
Debug: Service[nfs-lock](provider=upstart): Could not find nfs-lock.sh in /etc/init
Debug: Service[nfs-lock](provider=upstart): Could not find nfs-lock.sh in /etc/init.d
Error: /Stage[main]/Nfs::Client::Service/Service[nfs-lock]: Could not evaluate: Could not find init script or upstart conf file for 'nfs-lock'
Debug: Executing: '/sbin/status idmapd'
Debug: Executing: '/sbin/initctl --version'
Debug: Class[Nfs::Client::Service]: Resource is being skipped, unscheduling all events
Notice: /Stage[main]/Nfs::Client/Anchor[nfs::client::end]: Dependency Service[nfs-lock] has failures: true
Warning: /Stage[main]/Nfs::Client/Anchor[nfs::client::end]: Skipping because of failed dependencies
Debug: /Stage[main]/Nfs::Client/Anchor[nfs::client::end]: Resource is being skipped, unscheduling all events
Debug: Class[Nfs::Client]: Resource is being skipped, unscheduling all events

I removed nfs-lock from line 102 in params.pp haven't found anything that it is included in debian.

**Comment by derdanne** [comment]
i will remove nfs-lock in branch fix_rhel7_issues - checked in 12.04 and 14.04.

**Comment by derdanne** [comment]
merged to master
