### ISSUE TITLE
rpcidmapd service for centos 8

### ISSUE THREAD

**Issue by xm1234567** [derdanne/puppet-nfs#115]
Hello, Under centos 8, I notice 

> Error: /Stage[main]/Nfs::Client::Service/Service[rpcidmapd]/ensure: change from 'stopped' to 'running' failed: Systemd start for rpcidmapd failed!
journalctl log for rpcidmapd:

This client service seems not exist under CentOS 8.

Could you please check and adapt for  _operatingsystemmajrelease_ 8 please?

Thanks in advance

Xiaomei

**Comment by xm1234567** [comment]
I am using v2.1.2
and on my client,  there are bothe nfsv3 and nfsv4  mounts

**Comment by xm1234567** [comment]
I see there is a pull request already for RedHat8. If it is merged, it will solve my problem. So just  need to wait for the merge

**Comment by derdanne** [comment]
just released 2.1.3, PR is included
