### ISSUE TITLE
Domain in /etc/idmapd.conf is not always set correctly.

### ISSUE THREAD

**Issue by sandynomad** [derdanne/puppet-nfs#122]
If the /etc/idmapd.conf is incorrectly formatted:

    [General]
    Domain=wrong.domain.name
    Domain=right.domain.name

then the augeas lens fails to remove the incorrect domain name. **idmapd** appears to use the first `Domain=` found.

**Comment by derdanne** [comment]
Hey, thanks for your report! Unfortunately correcting wrong formatted configuration files is currently not in the scope of this module. 

Best regards
