### ISSUE TITLE
CentOS 8 and rpcidmapd

### ISSUE THREAD

**Issue by ivegotausername** [derdanne/puppet-nfs#123]
Rebuilt a test VM to CentOS 8, whilst retaining all the VM's puppet configuration from CentOS 7. Puppet errors with:

Error: Systemd start for rpcidmapd failed!
journalctl log for rpcidmapd:
-- Logs begin at Thu 2020-07-02 11:40:20 +03, end at Sun 2020-07-05 14:36:45 +03. --
-- No entries --

Error: /Stage[main]/Nfs::Client::Service/Service[rpcidmapd]/ensure: change from 'stopped' to 'running' failed: Systemd start for rpcidmapd failed!
journalctl log for rpcidmapd:
-- Logs begin at Thu 2020-07-02 11:40:20 +03, end at Sun 2020-07-05 14:36:45 +03. --
-- No entries --

Updated to latest derdanne/puppet-nfs, but problem still remained. Creating a symbolic link /usr/lib/systemd/system/rpcidmapd.service -> nfs-idmapd.service was the quick fix.

**Comment by derdanne** [comment]
Hi! 

In the params.pp we have `$server_nfsv4_servicehelper = [ 'nfs-idmapd.service' ]` ... Can you please check the facter variables `osfamily` and `operatingsystemmajrelease`?

Best regards!

**Comment by ivegotausername** [comment]
Hi

As requested:

# facter osfamily
RedHat
# facter operatingsystemmajrelease
8

**Comment by derdanne** [comment]
Hi, thanks! 

I would expect that it uses nfs-idmapd.service then... I'll have to test this locally. 

Which puppet and module version do you use, and what is your module configuration?

Best regards

**Comment by ivegotausername** [comment]
Puppet Agent 6.16.0
Puppet Server 6.11.1
derdanne-nfs 2.1.5

Not sure exactly what you mean by "module configuration", but the module is called with:

include ::nfs
... plus some custom code to configure automount. This node is an NFS client only.  In the global Hiera config, we have:

nfs::nfs_v4_client: true
nfs::nfs_v4_idmap_domain: '<our domain name>'
nfs::client_enabled: true
nfs::client_nfsv4_options: 'tcp,nolock,rsize=32768,wsize=32768,intr,noatime,actimeo=3,sec=sys'

I think that's everything! No additional client specific Hiera for this node.

**Comment by derdanne** [comment]
Hi,

i can't reproduce this on a local environment. Also the acceptance tests for CentOS 8 do not show the problem stated above (https://travis-ci.org/github/derdanne/puppet-nfs/jobs/730673592). 

Since  "rpcidmapd" is only in the fallback (default), i think there is something with your facter not working properly.
