### ISSUE TITLE
Potential vulnerabilities in Puppet files: Hard-coded Secret

### ISSUE THREAD

**Issue by cantebigene** [derdanne/puppet-nfs#125]
7 hard-coded secrets were found in 3 different scripts.

Script 1: https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/params.pp
 - Line [116](https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/params.pp#L116): `nfs_v4_idmap_nobody_user=nobody`
 - Line [184](https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/params.pp#L184): `nfs_v4_idmap_nobody_user=nobody`
 - Line [268](https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/params.pp#L268): `nfs_v4_idmap_nobody_user=nobody`
 - Line [284](https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/params.pp#L284): `nfs_v4_idmap_nobody_user=nobody`
 - Line [300](https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/params.pp#L300): `nfs_v4_idmap_nobody_user=nobody`

Script 2: https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/client/config.pp
 - Line [83](https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/client/config.pp#L83): `_user=set mapping/nobody-user `

Script 3: https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/server/config.pp
 - Line [63](https://github.com/derdanne/puppet-nfs/blob/4c16fa06a59f70f15d7d4b23299d821b68706983/manifests/server/config.pp#L63): `_user=set mapping/nobody-user `

A secret can be a password, user name, or private cryptographic key. 

This type of smell can lead to well-known types of vulnerabilities, as documented by CWE ([CWE-798](https://cwe.mitre.org/data/definitions/798.html) and [CWE-259](https://cwe.mitre.org/data/definitions/259.html)). Hard-coded secrets can be used to bypass protection mechanisms, gain privileges on applications and access to sensitive data. 

Storing secrets in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
To protect/manage your secrets, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your secrets by variables from the vault. For instance, replace`$password = ‘12345’` by `$password = $vault::password`. Thus, your secrets will no longer be disclosed publicly.

**Comment by derdanne** [comment]
N/A
