### ISSUE TITLE
.git folder in release archive

### ISSUE THREAD

**Issue by arlt** [derdanne/puppet-nfs#126]
It is a bit strange that the release archive contains a .git folder.

**Comment by jadestorm** [comment]
Unfortunately with the .git folder in the archive, it makes r10k install the module every time it runs, which is occasionally problematic.

**Comment by derdanne** [comment]
Ok, something changed in the release creation with the puppet cli, it started with version 2.1.3. I'll have to check why this happens.

**Comment by jadestorm** [comment]
Yeah y'all definitely aren't the only ones I've seen this happen on.  =)  As far as I can tell it doesn't happen with pdk -- but then I also didn't know you could still build releases with puppet cli.  However knowing that helps a lot for when I need to report this to other projects!  (even the current version of puppetlabs/ruby does it)

**Comment by derdanne** [comment]
Fixed with 2.1.6
