### ISSUE TITLE
RHEL9 drops /etc/sysconfig/nfs

### ISSUE THREAD

**Issue by jcpunk** [derdanne/puppet-nfs#139]
According to the RHEL9 release notes, `/etc/sysconfig/nfs` is no longer supported in RHEL9.  Folks are advised to use `/etc/nfs.conf` and `/etc/nfsmount.conf`

**Comment by jcpunk** [comment]
I ended up building : https://github.com/jcpunk/puppet-nfs

**Comment by derdanne** [comment]
Thanks for the info!
