### ISSUE TITLE
nfs_v4_client parameter not working as expected.

### ISSUE THREAD

**Issue by nvergottini** [derdanne/puppet-nfs#149]
The documentation for the nfs_v4_client parameter states the following.

> Boolean. If set to true, this module will use nfs version 4 for mounting nfs resources. If set to false it will use nfs version 3 to mount nfs resources. **It defaults to the setting of nfs_v4**

That is not accurate because if you set nfs_v4, it is not inherited by nfs_v4_client because nfs_v4_client is actually inheriting from nfs::params::nfs_v4.

**Comment by derdanne** [comment]
Clarified in docs (#160 )
