### ISSUE TITLE
augeasproviders_shellvar?

### ISSUE THREAD

**Issue by arlt** [derdanne/puppet-nfs#152]
I didn't find the use of `augeasproviders_shellvar` in the code.
If i am right, please remove https://github.com/derdanne/puppet-nfs/blob/master/metadata.json#L15

**Comment by MartyEwings** [comment]
I thought the same initially, but found the lens being consumed here:

        lens    => 'Shellvars.lns',

**Comment by arlt** [comment]
@MartyEwings ahh - many thanks!
