### ISSUE TITLE
Jammy - Ubuntu22.04 support ?

### ISSUE THREAD

**Issue by JoeriBouchet** [derdanne/puppet-nfs#153]
This version fails on Jammy because the nfsv4_servicehelper is set to the default idmapd in params, which does not exist in ubuntu. 
Is there any view on when Jammy tests are finished and the module is supported? 

error:
Error: Systemd start for idmapd failed!
journalctl log for idmapd:
-- No entries --

Error: /Stage[main]/Nfs::Server::Service/Service[idmapd]/ensure: change from 'stopped' to 'running' failed: Systemd start for idmapd failed!
journalctl log for idmapd:
-- No entries --

**Comment by derdanne** [comment]
Hey, are there any differences between 20.04 and 22.04?

**Comment by JoeriBouchet** [comment]
Thx for the reply, I will clone, test and get back to you.

**Comment by tobixen** [comment]
I will test it in #157

**Comment by tobixen** [comment]
The patch in #157 works for me at least, but I haven't studied in details if there are any changes between focal and jammy.

**Comment by tobixen** [comment]
This issue can probably be closed now?

**Comment by derdanne** [comment]
Yes, thanks!
