### ISSUE TITLE
Update deprecated dependencies

### ISSUE THREAD

**Issue by MartyEwings** [derdanne/puppet-nfs#154]
The following modules":  

 {"name":"herculesteam/augeasproviders_core","version_requirement":">= 2.1.5 < 4.0.0"},
    {"name":"herculesteam/augeasproviders_shellvar","version_requirement":">= 1.2.0 < 5.0.0"}

Are no longer maintained, and the projects have been moved to voxpupill:

puppet/augeasproviders_core

puppet/augeasproviders_shellvar

**Comment by derdanne** [comment]
Thanks!
