### ISSUE TITLE
Error when not managing server

### ISSUE THREAD

**Issue by robinbowes** [derdanne/puppet-nfs#2]
I'm only using the client-side functionslity of the module (my server is a SmartOS box).

I see this error when I run puppet:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Service[rpcbind] { subscribe => Concat[/etc/exports] }, because Concat[/etc/exports] doesn't seem to be in the catalog
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I can "fix" this by commenting out line 25 (and 34 for nfs v3) of manifests/client/service.pp:
```
...
 24       hasstatus  => $::nfs::client_services_hasstatus,
 25       #subscribe  => [ Concat[$::nfs::exports_file], Augeas[$::nfs::idmapd_file] ]
 26     }
...
```

I've not spent any time looking at a more elegant solution yet.

**Comment by derdanne** [comment]
Hi @robinbowes 

I created a branch https://github.com/derdanne/puppet-nfs/tree/fix-client-only-service-subscription. The changes needed are already there, but i need to fix testing, and optimize the code a little bit.

I'll try to work on it this week.

**Comment by derdanne** [comment]
Hi @robinbowes,

i fixed the testing and optimized the code in client/service.pp, can you please test if that solved your problems?

**Comment by robinbowes** [comment]
Will do. Am away for a week, will take a look when I get home. Thanks!

**Comment by derdanne** [comment]
Hey @robinbowes, 

any updates on this topic?

**Comment by derdanne** [comment]
I tested it, and it works in a client only setup now. I will merge the branch into the master and close this issue. If you have any further problems please reopen.
