### ISSUE TITLE
More issues with nfs-idmapd.service on RHEL7

### ISSUE THREAD

**Issue by greigm** [derdanne/puppet-nfs#23]
I see there have been a few closed issues on this, but I still have a related problem.

With the configuration:

```
  class { '::nfs':
    server_enabled => false,
    client_enabled => true,
    nfs_v4_client  => true,
  }

  nfs::client::mount { '/mnt/nfs_storage':
    server => 'some.server.somewhere',
    share  => '/path/to/share',
  }
```

I get the following:

```
Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind.service]/enable: enable changed 'false' to 'true'
Error: Could not enable nfs-idmap.service:
Error: /Stage[main]/Nfs::Client::Service/Service[nfs-idmap.service]/ensure: change from stopped to running failed: Could not enable nfs-idmap.service:
```

**Comment by derdanne** [comment]
Hey, i will take a look at this in the next week.

**Comment by greigm** [comment]
This might help (last comment): https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/1428961

**Comment by derdanne** [comment]
OK, then it might be sufficient to remove it from $server_nfsv4_servicehelper, i will try that.

**Comment by derdanne** [comment]
That worked in my local environment, i pushed to https://github.com/derdanne/puppet-nfs/tree/rhel7_nfs-idmapd.service_fix.

I will merge the branch and release a new version on forge when testing is green.

**Comment by derdanne** [comment]
Merged to master
