### ISSUE TITLE
puppet-nfs fails on Fedora 22

### ISSUE THREAD

**Issue by KrystianMarek** [derdanne/puppet-nfs#29]
On Fedora 22 nfs service is called nfs-server

from facter:
```
name => "Fedora",
  release => {
    full => "22",
    major => "22"
  }
```

[root@master ~]# systemctl is-enabled nfs-server
enabled
[root@master ~]# systemctl is-enabled nfs
disabled

**Comment by derdanne** [comment]
Thanks for the report, i will take a look at it.

**Comment by derdanne** [comment]
Hey, i took a look at it, but i am not very familiar with fedora and this module has not yet support for Fedora. 

Could you do a PR with the needed additions in params.pp to add the support for Fedora?

Workaround should be to use the parameter "$server_service_name" for overwriting the service name from params.pp.

**Comment by derdanne** [comment]
@KrystianMarek 

Please reopen, when this is still relevant for you.
