### ISSUE TITLE
rpcbind changes on every run 'false' to 'true'

### ISSUE THREAD

**Issue by bissa** [derdanne/puppet-nfs#30]
On Ubuntu 16.04 rpcbind changes on every run 'false' to 'true'

Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind]/enable: enable changed 'false' to 'true'

class { '::nfs':
    server_enabled      => false,
    client_enabled      => true,
    nfs_v4_client       => true,
    nfs_v4_idmap_domain => $::domain,
  }
  nfs::client::mount { '/volume1/nfs':
    server => 'nfs01',
    share  => '/volume1/nfs',
  }

service rpcbind status 
● rpcbind.service - RPC bind portmap service
   Loaded: loaded (/lib/systemd/system/rpcbind.service; indirect; vendor preset: enabled)
  Drop-In: /run/systemd/generator/rpcbind.service.d
           └─50-rpcbind-$portmap.conf
   Active: active (running) since Thu 2016-06-30 16:34:55 CEST; 47min ago
 Main PID: 12678 (rpcbind)
   CGroup: /system.slice/rpcbind.service
           └─12678 /sbin/rpcbind -f -w

Jun 30 16:34:55 host01 systemd[1]: Starting RPC bind portmap service...
Jun 30 16:34:55 host01 systemd[1]: Started RPC bind portmap service.

**Comment by derdanne** [comment]
Thanks for the report, i will take a look at it.

**Comment by bissa** [comment]
Great

Some more info 
puppet --version
4.5.2

puppetserver version: 2.4.0

**Comment by trunet** [comment]
This is systemd/puppet related.

    # systemctl list-unit-files | grep rpcbind
    rpcbind.service                        static  
    rpcbind.socket                         enabled 
    rpcbind.target                         static 

    # systemctl is-enabled rpcbind
    indirect

puppet runs is-enabled, and try to enable the service, that is an indirect service.

Check this:
https://github.com/echocat/puppet-nfs/blob/master/manifests/client/redhat/service.pp

If version 7, enable should be undef.

**Comment by bissa** [comment]
Seems to be solved with puppet version 4.6.0

**Comment by derdanne** [comment]
Oh, that are great news - sorry for the delay, i would have liked to resolve this earlier...
