### ISSUE TITLE
Fails mounting exported resources

### ISSUE THREAD

**Issue by nexix** [derdanne/puppet-nfs#34]
Exported resource mounts currently do not work -

server/export.pp

@@nfs::client::mount {  "shared ${v4_export_name} by ${::clientcert}":
  ensure        => $ensure,
  remounts      => $remounts,
  atboot        => $atboot,
  options_nfsv4 => $options_nfsv4,
  bindmount     => $bindmount,
  nfstag        => $nfstag,
  share         => $v4_export_name,
  server        => $::clientcert,
  mount         => $mount,
}

client/mount.pp

define nfs::client::mount (
  $server,
  $share            = undef,
  $ensure           = 'mounted',
  $mount            = $title,
  $remounts         = false,
  $atboot           = false,
  $options_nfsv4    = $::nfs::client_nfsv4_options,
  $options_nfs      = $::nfs::client_nfs_options,
  $bindmount        = undef,
  $nfstag           = undef,
  $nfs_v4           = $::nfs::client::nfs_v4,
  $owner            = undef,
  $group            = undef,
  $mode             = undef,
  $mount_root       = undef,

mount { "shared ${sharename} by ${server} on ${mount}":
  ensure   => $ensure,
  device   => "${server}:${sharename}",
  fstype   => $::nfs::client_nfsv4_fstype,
  name     => $mount,
  options  => $options_nfsv4,
  remounts => $remounts,
  atboot   => $atboot,
  require  => Nfs::Functions::Mkdir[$mount],
}

Currently the mount resource in client/mount.pp uses name => $mount which then resolves to the $title variable passed from the exported resource. The mount resource then attempts to mount "shared /mount_name by clientcert" based on server/export.pp.

$mount = $title needs to be changed to $mount = $share in client/mount.pp based on the parameters in the exported resource.

PuppetDB output -

 "parameters" : {
    "share" : "/export",
    "atboot" : false,
    "ensure" : "mounted",
    "server" : "fqdn.fqdn.fqdn",
    "remounts" : false,
    "options_nfs" : "tcp,nolock,rsize=32768,wsize=32768,intr,noatime,actimeo=3"
  },

**Comment by derdanne** [comment]
hey, thanks for the report, i think the best way without losing compatibility to existing setups, would be to change the export of resources like:

    if $mount != undef {
      $mount_name = $mount
    } else {
      $mount_name = $v4_export_name
    }

    @@nfs::client::mount { $mount_name:
      ensure        => $ensure,
      remounts      => $remounts,
      atboot        => $atboot,
      options_nfsv4 => $options_nfsv4,
      bindmount     => $bindmount,
      nfstag        => $nfstag,
      share         => $v4_export_name,
      server        => $::clientcert,
    }

What do ypu think about this?

**Comment by nexix** [comment]
I believe that will work since all mount export names should be unique the way this is structured.

**Comment by derdanne** [comment]
I've pushed the changes to https://github.com/derdanne/puppet-nfs/tree/fix_mounting_exported_resources, could you please verify the patch?

**Comment by nexix** [comment]
Tested exported resources and static values and both work fine.  Thank you very much for your help.

**Comment by derdanne** [comment]
Merged to master
