### ISSUE TITLE
how do i define mounts via hiera for an nfs client?

### ISSUE THREAD

**Issue by mikedevita** [derdanne/puppet-nfs#44]
im trying to install and mount some nfsv3 mounts client side but cant get it to run. it just doesnt detect that the nfs is applied to my node.

```
classes:
  - nfs
```

given the following mount point i'd expect it to mount, but i dont think i have the syntax right.

```
nfs::client::mount:
  '/opt/software':
    server: '192.168.10.12'
    share: "/mnt/VAULT/Software"
    ensure: mounted
    options: 'rw,nolock,hard,intr'
```

**Comment by derdanne** [comment]
Hi,

you should set "nfs::client_enabled: true" on your client node.

**Comment by mikedevita** [comment]
i did that but using foreman, there is no nfs::client::mount available so i cant assigned my mounts in foreman.

![image](https://cloud.githubusercontent.com/assets/2991640/19204932/48ab8352-8c94-11e6-875f-f2e212c78f60.png)

**Comment by derdanne** [comment]
Hey, sorry i am not familiar with puppet setup in foreman - you shuold have more success to get an usefull answer, when asking in puppet irc or slack.
