### ISSUE TITLE
 options changed 'rbind' to 'rbind' on every puppet-agent run

### ISSUE THREAD

**Issue by harvey637** [derdanne/puppet-nfs#46]
Hi Daniel,
this is more a question than a productive blocking issue:
On an nfsv4 server ther are notices, that every exported directory gets 
`options changed 'rbind' to 'rbind'`
and then is remounted.
Complete listing for one export:
```
Notice: /Stage[main]/Main/Node[ftp-repo]/Nfs::Server::Export[/ps/storage/mercury/mercury]/Nfs::Functions::Nfsv4_bindmount[/ps/storage/mercury/mercury]/Mount[/export/mercury]/options: options changed 'rbind' to 'rbind'
Info: /Stage[main]/Main/Node[ftp-repo]/Nfs::Server::Export[/ps/storage/mercury/mercury]/Nfs::Functions::Nfsv4_bindmount[/ps/storage/mercury/mercury]/Mount[/export/mercury]: Scheduling refresh of Mount[/export/mercury]
Info: Mount[/export/mercury](provider=parsed): Remounting
Notice: /Stage[main]/Main/Node[ftp-repo]/Nfs::Server::Export[/ps/storage/mercury/mercury]/Nfs::Functions::Nfsv4_bindmount[/ps/storage/mercury/mercury]/Mount[/export/mercury]: Triggered 'refresh' from 1 events
Info: /Stage[main]/Main/Node[ftp-repo]/Nfs::Server::Export[/ps/storage/mercury/mercury]/Nfs::Functions::Nfsv4_bindmount[/ps/storage/mercury/mercury]/Mount[/export/mercury]: Scheduling refresh of Mount[/export/mercury]

```
Module
derdanne/nfs v 1.0.1

puppetcode:
```
   class { '::nfs':
      server_enabled => true,
      nfs_v4         => true,
   }
...
   nfs::server::export{ '/ps/storage/mercury/mercury':
      ensure  => 'mounted',
      clients => 'mercury-*(rw,insecure,no_subtree_check,async,no_root_squash)',
      v4_export_name => "mercury",
   }

```
fstab (filled automatic):
```
/ps/storage/mercury/mercury     /export/mercury none    rbind   0       0
```

System:
centos6

Thank you

**Comment by derdanne** [comment]
Hi, could you please post the output of `mount | grep "/export/mercury"`?

**Comment by harvey637** [comment]
Hi,
here you are:
```
[root@ftp-repo ~]# mount | grep /export/mercury
/ps/storage/mercury/mercury on /export/mercury type none (rw,bind)
[root@ftp-repo ~]#
```

**Comment by harvey637** [comment]
ups, sorry to close

**Comment by harvey637** [comment]
ok, I see what you are looking for.

**Comment by harvey637** [comment]
ok, I did unmount /export/mercury - now unmounted.
```
[root@ftp-repo ~]# umount /export/mercury
umount: /export/mercury: not mounted
[root@ftp-repo ~]# grep mercury /etc/fstab
/ps/storage/mercury/mercury     /export/mercury none    rbind   0       0
[root@ftp-repo ~]# mount -a
[root@ftp-repo ~]# mount | grep /export/mercury
/ps/storage/mercury/mercury on /export/mercury type none (rw,bind)
```
so it looks, like rbind is not working, or simply replaced with bind.

**Comment by harvey637** [comment]
Hmmmm, it looks like there is no rbind in /etc/fstab, only bind ???

**Comment by harvey637** [comment]
ok, I added:       bind => 'bind',
to the exports, run puppet-agent twice and no more notices/remounts.
This dirty solves it, as I at this time do not have submounts and therefor dont really need rbind.
But in future this will be possible and will get into mystical problems like forgetting about submount.

Nothing You can do.

Thank You for Your time and pointing me to some unexpected sideproblem in fstab.

**Comment by derdanne** [comment]
Thanks for the information, i am wondering why there is no rbind in Centos fstab, do you know if "bind" fstype behaves like rbind?

**Comment by harvey637** [comment]
hmm, just thinking:
maybe there is rbind in fstab (actually it is there and mount does not complain), 
BUT mount does not display the difference between rbind and bind, as both are mounts of type 'bind'.

As consequence puppet finds (with the command mount) the type 'bind', wants to remount and 
changed the fstab, but inside fstab it is already correct. So the notice says change 'rbind' to 'rbind'. 
first rbind read from fstab, second rbind read from puppet.

Im investigating a biit deep with submounts, but my playing around created some production problems :-(

**Comment by harvey637** [comment]
Still a bit confused, but some information (other server, same situation). Strange things happen:
mounted bind subdir "ora" on directory "artifactory/ora", can see file inside "artifactory/backup" and 
"artifactory/ora" (first mountlevel)
mounted bind "artifactory" to /export/artifactory" -> "artifactory/ora" EMPTY below /export/artifactory!
mounted rbind "artifactory" to /export/artifactory" -> "artifactory/ora" FILLED below /export/artifactory!
this is the expected behaviour.
keeping the rbind, but unmount "artifactory/ora" -> STILL FILLED /export/artifactory/ora !!! ??? !!!
even writing works, files are inside the top "ora" directory !?!
This is strange. But this is all LOCAL filesystem, 
exported with NFS /artifactory/ora" is NEVER filled.
Also the sequence of mount is important.

With NFS I guess that nfs_options "crossmnt" come into play, it is not sufficient only to rbind!!!
SO what works:
```
   nfs::server::export{ '/ps/nfs/artifactory':
      ensure  => 'mounted',
      clients => 'dev*(rw,insecure,no_subtree_check,async,no_root_squash,crossmnt)',
   }
```
so rbind works for local filesystem, but not for nfs. 
and it is important to use rbind inside fstab! even if command mount does only show bind!
with bind in fstab subfolder is not visible! only with rbind. This looks like an error to me!!!

But we are talking NFS, soif the subdir is mounted correct with rbind (checked on local filesystem)
then it is necessarry to use "crossmnt" as nfsoption.
THIS was the only solution, that nfs-transported server-sided-subdir to the  client.

Confusing not not quite intuitive. Also to make it work I had a lot of timeouts and nfs restarts to do to remove stale links.

Now for me this issue is finished, does not work as expected, but this is not your fault.
There is nothing you can do, but hint the "crossmnt" in your documentation.

You improved my linux low level knowledge into some very dark regions.

**Comment by derdanne** [comment]
Thanks for digging deep inside of mount behaviour! 

I will definitely add some documentation about "crossmnt" parameter.

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind

**Comment by derdanne** [comment]
I've updated the README

https://github.com/derdanne/puppet-nfs/blob/master/README.md#bind
