### ISSUE TITLE
Add an option to disable exported resources

### ISSUE THREAD

**Issue by gmenuel** [derdanne/puppet-nfs#47]
When using puppet without a puppet master you might not want to configure storeconfigs, but in this case puppet will print warnings : "Warning: You cannot collect exported resources without storeconfigs being set" for export.pp:145. Could it be possible to add an option allowing to avoid creating exported resources ?

**Comment by derdanne** [comment]
I will take a look at it, thanks for reporting.

**Comment by derdanne** [comment]
Fixing in https://github.com/derdanne/puppet-nfs/tree/disable_storeconfigs

**Comment by derdanne** [comment]
Add parameter storeconfigs_enabled, just set it to false to disabel exporting of resources.
