### ISSUE TITLE
Dependency problem for `nfs::client::mount` defined type

### ISSUE THREAD

**Issue by gettalong** [derdanne/puppet-nfs#48]
There should be a dependency on the client package on lines https://github.com/derdanne/puppet-nfs/blob/master/manifests/client/mount.pp#L115 and https://github.com/derdanne/puppet-nfs/blob/master/manifests/client/mount.pp#L142, e.g. on `nfs-common` in case of Debian/Ubuntu.

Otherwise the mount command may be executed before the client package, that contains the `mount.nfs[4]` command, is installed.

**Comment by derdanne** [comment]
Thanks for the report, i will add the dependency in the next release.

**Comment by derdanne** [comment]
I'll work in the branch https://github.com/derdanne/puppet-nfs/tree/client_mount_package_dep on this issue.

**Comment by derdanne** [comment]
Fixed and merged into master

**Comment by gettalong** [comment]
Thank you!
