### ISSUE TITLE
RHEL7 NFS Server, required service rpcbind which was not preinstalled and started

### ISSUE THREAD

**Issue by taz-gnu** [derdanne/puppet-nfs#5]
I'm testing using this puppet nfs module to manage a nfs server for me. 

When I puppet apply the following test case, I get errors due to rpcbind not pre-existing. 
class { '::nfs':
      ensure => present,
      server_enabled => true,
      nfs_v4         => true,
      nfs_v4_export_root_clients =>
        '10.0.0.0/8(rw,fsid=root,insecure,no_subtree_check,async,no_root_squash)'
    }
nfs::server::export{ '/home':
      ensure  => 'mounted',
      clients => '10.0.0.0/8(rw,insecure,no_subtree_check,async,no_root_squash) localhost(rw)'
  }

I see the client class covers rpcbind. If I run the following client test before the above server one rpcbind errors are cleared. 
class { '::nfs':
    server_enabled => false,
    client_enabled => true,
    nfs_v4         => true,
    nfs_v4_idmap_domain => $::domain,
  }

Should I configuring rpcbind or use a separate puppet module for it when setting up a server? Please advise.

**Comment by derdanne** [comment]
Hey, could you try the server example without the parameter "ensure => present,". You won't need to set this value by yourself, and its causing failures in spec tests when it is set.

**Comment by taz-gnu** [comment]
remove "ensure => present," with similar results, still errors starting nfs-idmap and nfs-server. 
also confirmed that rpcbind was not running and '/bin/systemctl start nfs-server' returned 1 and that nfs-server started with 0 after starting rpcbind.
note, i when back to the current master release for this check. 

looks like this: 

[root@testbox]# puppet apply tests/server.pp 
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Warning: You cannot collect without storeconfigs being set on line 54 in file /etc/puppet/modules/nfs/manifests/server/config.pp
Warning: You cannot collect without storeconfigs being set on line 101 in file /etc/puppet/modules/nfs/manifests/server/export.pp
Warning: You cannot collect without storeconfigs being set on line 117 in file /etc/puppet/modules/nfs/manifests/server/export.pp
Notice: Compiled catalog for rhel7-taz.usask.ca in environment production in 0.66 seconds
Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
   (at /usr/share/ruby/vendor_ruby/puppet/type.rb:816:in `set_default')
Notice: /Stage[main]/Nfs::Server::Package/Package[nfs-utils]/ensure: created
Notice: /Stage[main]/Nfs::Server::Package/Package[nfs4-acl-tools]/ensure: created
Notice: /Stage[main]/Nfs::Server::Config/Augeas[/etc/idmapd.conf]/returns: executed successfully
Notice: /File[/export]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /File[/export/home]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /Stage[main]/Main/Nfs::Server::Export[/home]/Nfs::Functions::Nfsv4_bindmount[/home]/Mount[/export/home]/ensure: defined 'ensure' as 'mounted'
Notice: /Stage[main]/Main/Nfs::Server::Export[/home]/Nfs::Functions::Nfsv4_bindmount[/home]/Mount[/export/home]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Nfs::Server::Config/Concat[/etc/exports]/File[/etc/exports]/content: content changed '{md5}d41d8cd98f00b204e9800998ecf8427e' to '{md5}4e0f60acd7acdb22cf84cd7e91e7d32a'
Error: Could not start Service[nfs-idmap]: Execution of '/bin/systemctl start nfs-idmap' returned 1: Job for nfs-idmapd.service failed. See 'systemctl status nfs-idmapd.service' and 'journalctl -xn' for details.
Wrapped exception:
Execution of '/bin/systemctl start nfs-idmap' returned 1: Job for nfs-idmapd.service failed. See 'systemctl status nfs-idmapd.service' and 'journalctl -xn' for details.
Error: /Stage[main]/Nfs::Server::Service/Service[nfs-idmap]/ensure: change from stopped to running failed: Could not start Service[nfs-idmap]: Execution of '/bin/systemctl start nfs-idmap' returned 1: Job for nfs-idmapd.service failed. See 'systemctl status nfs-idmapd.service' and 'journalctl -xn' for details.
Notice: /Stage[main]/Nfs::Server::Service/Service[nfs-idmap]: Triggered 'refresh' from 2 events
Error: Could not start Service[nfs-server]: Execution of '/bin/systemctl start nfs-server' returned 1: Job for nfs-server.service failed. See 'systemctl status nfs-server.service' and 'journalctl -xn' for details.
Wrapped exception:
Execution of '/bin/systemctl start nfs-server' returned 1: Job for nfs-server.service failed. See 'systemctl status nfs-server.service' and 'journalctl -xn' for details.
Error: /Stage[main]/Nfs::Server::Service/Service[nfs-server]/ensure: change from stopped to running failed: Could not start Service[nfs-server]: Execution of '/bin/systemctl start nfs-server' returned 1: Job for nfs-server.service failed. See 'systemctl status nfs-server.service' and 'journalctl -xn' for details.
Notice: /Stage[main]/Nfs::Server::Service/Service[nfs-server]: Triggered 'refresh' from 2 events
Notice: /Stage[main]/Nfs::Server/Anchor[nfs::server::end]: Dependency Service[nfs-server] has failures: true
Notice: /Stage[main]/Nfs::Server/Anchor[nfs::server::end]: Dependency Service[nfs-idmap] has failures: true
Warning: /Stage[main]/Nfs::Server/Anchor[nfs::server::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 10.88 seconds

**Comment by derdanne** [comment]
OK, i need to debug this on an RHEL7 machine. Since i have none, do you have any suggestions about a vagrant box or something like that?

**Comment by taz-gnu** [comment]
I'm using a fresh RHEL7.1 test box. I see a 'CentOS7.0 x86_64 Puppet and Docker' at http://www.vagrantbox.es/ that should fit the bill. Haven't checked it out as its a virtual box machine & i'm running vmware ws. Can check it out for you if you'd like or if it doesn't react the same.

**Comment by derdanne** [comment]
Hey, sorry for the delay! I was really busy in the last weeks. I'll try to get this solved till the end of next week.

**Comment by taz-gnu** [comment]
I have picked up work on disk provisioning and user automation for this service with the plan to circle back to puppet, so no rush from our end.   

Thanks for providing and maintaining this module.  appreciated

**Comment by derdanne** [comment]
OK, i got a centos vagrant box up  and fixed this issue, the correct service names in Redhat-7 family are:

rpcbind.service, nfs-idmap.service, nfs-server.service

This fixed the described issues for me - i will push to the branch fix_rhel7_issues, could you please verify  the fix?

**Comment by derdanne** [comment]
since all my tests with your example manifests work, i merged the fixes to master.
