### ISSUE TITLE
Static ports / server threads configuration bits

### ISSUE THREAD

**Issue by poikilotherm** [derdanne/puppet-nfs#51]
Hi Daniel,

first of all: thanks for your great work on this module! :-) I would like to ensure my NFS server behaves well in combination with my firewall, thus I need to configure things.

Would you think that configuring static ports for nfs / rpcbind / nfs-kernel-server would be within the scope of this module?

What about the server threads? Is this beyond the scope of this module?

Cheers,
Oliver

Reference:
1. https://www.stephenrlang.com/2015/12/setup-nfsv3-on-ubuntu-or-debian/
2. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Storage_Administration_Guide/s2-nfs-nfs-firewall-config.html

**Comment by derdanne** [comment]
Hi Oliver,

thanks should go to all people which are participating in the work on this module.

We can do this within this module, to have a one-stop-shopping experience, and do all configuration needed in one scope.

These are settings we can achieve by manipulating the "defaults"-file of the nfs-server daemon. We have already the information about the location of the file for most of the supported operatingsystems. We could use an augeas scope that optionally setup these configuration options, as we do it already for the idmapd setting on the client side. We have to be careful, to only set this optionally and avoid collision with the augeas on the client side. Also we have to write some tests for these settings.

When you already have something in mind, feel totally free, to submit a pull request ;)

I can also add it as a feature request, then i will work on this topic as soon, as i have some time to spare.

Cheers back,
Daniel

**Comment by poikilotherm** [comment]
Yeah, please add the feature-request label for now as I don't have spare time right now. Then let's see who has some spare time first... ;-)

**Comment by laywah2016** [comment]
I have just found this module and currently using it on Fedora Server 28. Well done on the existing module and its support. Would also love to see these features.

**Comment by pearsondavid** [comment]
I've been using this module (CentOS 7) for a few months now and also found it to be great, thank you for this and keep up the great work! I'd also like to see these features included, I found that LOCKD_TCPPORT and LOCKD_UDPPORT weren't set and changing upon restart / reboot.
