### ISSUE TITLE
Syntax error at 'Enum'; expected ')' at /etc/puppet/environments/colt_dev/modules/nfs/manifests/init.pp:169

### ISSUE THREAD

**Issue by saraswathikm** [derdanne/puppet-nfs#54]
Syntax error at 'Enum'; expected ')' at /etc/puppet/environments/colt_dev/modules/nfs/manifests/init.pp:169

**Comment by derdanne** [comment]
Hi,

thanks for the PR. Could you give me some informations about your environment (peuppet version, ... )?

**Comment by saraswathikm** [comment]
HI,

Puppet is 3.x, as per the below description. I have tag to use 1.0.2 version of puppet-nfs.





+When you are using a puppet version 3.x like it is shipped with Redhat Satellite 6, please use a version 1.x.x from puppet forge







+or the branch puppet3 when cloning directly from Github. (Note: https://github.com/derdanne/puppet-nfs/pull/49#issuecomment-285091678)




Saraswathi K

Technical Lead

Saraswathi.k@aricent.com | Mobile +91 9741 775 479  | Office +91 80 4106 7914

[cid:image002.jpg@01D299AD.D298D8F0]<https://www.aricent.com/>

**Comment by derdanne** [comment]
OK, so Tag 1.0.2 / puppet3 branch works in your environment? 

When this does not work in your environment, could you please do a pull request on the puppet3 branch.

Thanks!

**Comment by saraswathikm** [comment]
Tagging to 1.0.2  did work. Thank you ☺

Saraswathi K

Technical Lead

Saraswathi.k@aricent.com | Mobile +91 9741 775 479  | Office +91 80 4106 7914

[cid:image002.jpg@01D299B0.4F0076D0]<https://www.aricent.com/>
