### ISSUE TITLE
RHEL7, nfs-idmap failed to start glitch

### ISSUE THREAD

**Issue by taz-gnu** [derdanne/puppet-nfs#6]
When I run the nfs-4 server set install
class { '::nfs':
ensure => present,
server_enabled => true,
nfs_v4 => true,
nfs_v4_export_root_clients =>
'10.0.0.0/8(rw,fsid=root,insecure,no_subtree_check,async,no_root_squash)'
}

I get the below error that nfs-idmap failed to start. 
Error: Could not start Service[nfs-idmap]: Execution of '/bin/systemctl start nfs-idmap' returned 1: Job for nfs-idmapd.service failed. See 'systemctl status nfs-idmapd.service' and 'journalctl -xn' for details.
Wrapped exception:
Execution of '/bin/systemctl start nfs-idmap' returned 1: Job for nfs-idmapd.service failed. See 'systemctl status nfs-idmapd.service' and 'journalctl -xn' for details.
Error: /Stage[main]/Nfs::Server::Service/Service[nfs-idmap]/ensure: change from stopped to running failed: Could not start Service[nfs-idmap]: Execution of '/bin/systemctl start nfs-idmap' returned 1: Job for nfs-idmapd.service failed. See 'systemctl status nfs-idmapd.service' and 'journalctl -xn' for details.
Notice: /Stage[main]/Nfs::Server::Service/Service[nfs-idmap]: Triggered 'refresh' from 2 events
Notice: /Stage[main]/Nfs::Server::Service/Service[nfs-server]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Nfs::Server/Anchor[nfs::server::end]: Dependency Service[nfs-idmap] has failures: true
Warning: /Stage[main]/Nfs::Server/Anchor[nfs::server::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 0.49 seconds

On investigation a check of /bin/systemctl status nfs-idmap shows that the service has been started. A rerun of the puppet apply tests/server.pp above run successfully finishing the server config. 

I there possibly a timing issue here?

**Comment by derdanne** [comment]
It seems that your systemctl exits with status "1" and not as expected from puppet with status "0". Could you please verify if this happens also without using puppet?

-> /bin/systemctl start nfs-idmap && echo $?

Maybe i have to set an execution order, could you investigate if rpcidmapd depends on the nfs-service daemon on Redhat?

**Comment by derdanne** [comment]
I added a starting order to start rpcidmapd after the nfs-server service, could you please try, if this solves your issue? (https://github.com/derdanne/puppet-nfs/tree/fix_rhel7_issues)

**Comment by taz-gnu** [comment]
Thanks derdanne. Am out of the office. will check tomorrow..

**Comment by taz-gnu** [comment]
The service start order on rhel7 is: rpcbind.service nfs-idmap.service nfs-server.service, see https://fedoraproject.org/wiki/User:Renich/HowTo/NFSv4 

As in other issue report things go sideways if rpcbind is not pre-started. with rpcbind up, if nfs-server is started first it starts nfs-idmap for you. 

after preinstalling and starting prcbind, with the fix_rhel7_issues branch I get: 

[root@testbox]# puppet apply tests/server.pp 
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Warning: You cannot collect without storeconfigs being set on line 54 in file /etc/puppet/modules/nfs/manifests/server/config.pp
Warning: You cannot collect without storeconfigs being set on line 101 in file /etc/puppet/modules/nfs/manifests/server/export.pp
Warning: You cannot collect without storeconfigs being set on line 117 in file /etc/puppet/modules/nfs/manifests/server/export.pp
Notice: Compiled catalog for rhel7-taz.usask.ca in environment production in 0.72 seconds
Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
   (at /usr/share/ruby/vendor_ruby/puppet/type.rb:816:in `set_default')
Notice: /Stage[main]/Nfs::Server::Package/Package[nfs-utils]/ensure: created
Notice: /Stage[main]/Nfs::Server::Package/Package[nfs4-acl-tools]/ensure: created
Notice: /Stage[main]/Nfs::Server::Config/Augeas[/etc/idmapd.conf]/returns: executed successfully
Notice: /File[/export]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /File[/export/home]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /Stage[main]/Main/Nfs::Server::Export[/home]/Nfs::Functions::Nfsv4_bindmount[/home]/Mount[/export/home]/ensure: defined 'ensure' as 'mounted'
Notice: /Stage[main]/Main/Nfs::Server::Export[/home]/Nfs::Functions::Nfsv4_bindmount[/home]/Mount[/export/home]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Nfs::Server::Config/Concat[/etc/exports]/File[/etc/exports]/content: content changed '{md5}d41d8cd98f00b204e9800998ecf8427e' to '{md5}4e0f60acd7acdb22cf84cd7e91e7d32a'
Error: Could not start Service[nfs-service]: Execution of '/bin/systemctl start nfs-service' returned 6: Failed to issue method call: Unit nfs-service.service failed to load: No such file or directory.
Wrapped exception:
Execution of '/bin/systemctl start nfs-service' returned 6: Failed to issue method call: Unit nfs-service.service failed to load: No such file or directory.
Error: /Stage[main]/Nfs::Server::Service/Service[nfs-service]/ensure: change from stopped to running failed: Could not start Service[nfs-service]: Execution of '/bin/systemctl start nfs-service' returned 6: Failed to issue method call: Unit nfs-service.service failed to load: No such file or directory.
Notice: /Stage[main]/Nfs::Server::Service/Service[nfs-service]: Triggered 'refresh' from 2 events
Notice: /Stage[main]/Nfs::Server::Service/Service[nfs-idmap]: Dependency Service[nfs-service] has failures: true
Warning: /Stage[main]/Nfs::Server::Service/Service[nfs-idmap]: Skipping because of failed dependencies
Notice: /Stage[main]/Nfs::Server::Service/Service[nfs-idmap]: Triggered 'refresh' from 2 events
Notice: /Stage[main]/Nfs::Server/Anchor[nfs::server::end]: Dependency Service[nfs-service] has failures: true
Warning: /Stage[main]/Nfs::Server/Anchor[nfs::server::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 6.56 seconds
[root@rhel7-taz nfs]# 

With the master branch nfs-server came up, nfs-idmap didnt, but a rerun broght it up as well. In this case the rerun fails in the same mannor.

**Comment by derdanne** [comment]
same her - see comment in https://github.com/derdanne/puppet-nfs/issues/5

**Comment by derdanne** [comment]
merged to master.
