### ISSUE TITLE
Questions on Client Mount on v4  using Hiera

### ISSUE THREAD

**Issue by sraja1010101010** [derdanne/puppet-nfs#60]
Hi Daniel,
This is more of a question rather than an issue really.
Thanks for your great work on this module! :-) I would like to ensure this section is working as expected on a v4? I was trying to use this on the client with Redhat version 6.8.

For the below config the heira is working on the server but not on the client.The heira call on the server is working as expected and working good but not on the client.  The binary is getting installed and the configs are getting updated on the client but not able to get the target NFS mount on the client .it looks like an export is missing here.It would be great if can validate the below configs.

class profiles::nfsserver {
  node 'nodnfs.posc.com'{
    hiera_include('classes')
    $nfs_exports_global = hiera_hash('nfs::nfs_exports_global', false)
    $defaults_nfs_exports = {
      ensure  => 'mounted',
      clients => '192.168.21.42(rw,insecure,no_subtree_check,async,no_root_squash)',
      nfstag     => $::fqdn,
    }
  }
  if $nfs_exports_global {
    create_resources('::nfs::server::export', $nfs_exports_global, $defaults_nfs_exports)
  }

  node 'nodnfsclient.posc.com' {
    hiera_include('classes')
    $nfs_server = hiera('nfs::nfs_server', false)
    if $nfs_server {
      Nfs::Client::Mount <<| nfstag == $nfs_server |>>
    }
  }
}

Client hiera setting 
classes:
  - nfs
nfs::client_enabled: true
nfs::nfs_v4_client: true
nfs::nfs_v4_idmap_domain: '%{::domain}'
nfs::nfs_v4_mount_root: '/application'
nfs::nfs_server: 'nodnfs.posc.com'

server hiera  setting 

classes:
  - nfs
nfs::server_enabled: true
nfs::client_enabled :  false
nfs::nfs_v4:  true
nfs::nfs_v4_idmap_domain:  '%{::domain}'
nfs::nfs_v4_export_root:  '/application'
nfs::nfs_v4_export_root_clients:  '192.168.21.42(rw,sync,no_root_squash,no_all_squash)'

Client puppet run...o/p
Notice: Local environment: 'development' doesn't match server specified node environment 'nfs', switching agent to 'nfs'.
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for nodnfsclient.posc.com
Info: Applying configuration version 'a84f0d45f11b9f51c4b52318817c826430384baa'
Notice: /Stage[main]/Nfs::Client::Package/Package[nfs-utils]/ensure: created
Info: /Stage[main]/Nfs::Client::Package/Package[nfs-utils]: Scheduling refresh of Service[rpcbind]
Info: /Stage[main]/Nfs::Client::Package/Package[nfs-utils]: Scheduling refresh of Service[rpcidmapd]
Notice: /Stage[main]/Nfs::Client::Package/Package[nfs4-acl-tools]/ensure: created
Info: /Stage[main]/Nfs::Client::Package/Package[nfs4-acl-tools]: Scheduling refresh of Service[rpcbind]
Info: /Stage[main]/Nfs::Client::Package/Package[nfs4-acl-tools]: Scheduling refresh of Service[rpcidmapd]
Notice: Augeas[/etc/idmapd.conf](provider=augeas):
--- /etc/idmapd.conf	2017-03-22 15:03:08.000000000 -0700
+++ /etc/idmapd.conf.augnew	2017-04-18 14:48:42.536398520 -0700
@@ -38,6 +38,7 @@
 # must be included in the list!
 #Local-Realms =

+Domain=posc.com
 [Mapping]

 Nobody-User = nobody

Notice: /Stage[main]/Nfs::Client::Config/Augeas[/etc/idmapd.conf]/returns: executed successfully
Info: /Stage[main]/Nfs::Client::Config/Augeas[/etc/idmapd.conf]: Scheduling refresh of Service[rpcbind]
Info: /Stage[main]/Nfs::Client::Config/Augeas[/etc/idmapd.conf]: Scheduling refresh of Service[rpcidmapd]
Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind]: Triggered 'refresh' from 3 events
Notice: /Stage[main]/Nfs::Client::Service/Service[rpcidmapd]: Triggered 'refresh' from 3 events
Notice: Applied catalog in 16.25 seconds

**Comment by sraja1010101010** [comment]
This is more of a question rather than an issue really.
Thanks for your great work on this module! :-) I would like to ensure this section is working as expected on a v4? I was trying to use this on the client with Redhat version 6.8. it is working

**Comment by derdanne** [comment]
Hey, 

sorry for not answering that - i was on vacations. I think the best place for configuration questions is the puppet irc or slack. You can find me also there as @derdanne.

Cheers!
