### ISSUE TITLE
Arch Linux rpc.idmapd name changed

### ISSUE THREAD

**Issue by darkfeline** [derdanne/puppet-nfs#65]
On Arch Linux, rpc.idmapd service is now called nfs-idmapd

Additionally, idmapd is no longer needed on the NFS client side (or so it appears to me after light research).

**Comment by derdanne** [comment]
I removed rpc.idmapd from $client_nfsv4_services, and renamed rpc.idmapd to nfs-idmapd in $server_nfsv4_servicehelper for archlinux in master branch.
