### ISSUE TITLE
rquotad service support

### ISSUE THREAD

**Issue by legooolas** [derdanne/puppet-nfs#67]
Would you be interested in a patch to add `rpc.rquotad` support to support remote quota queries, or is this something you see as not part of the remit of this module?

If so, would you want this as a specific option to enable `rquotad` or something using a hash of `server_services` similar to how the `client_services` hash works?

Happy to provide a patch if that would be useful   :)

(Currently I'm just manually adding a `service` entry to ensure this is running outside of the module)

**Comment by derdanne** [comment]
Hi @legooolas, 

thank you for enhancing this module. 

I think it would be best to have this activated with an own option for enabling it. We should have the service names via the default params class. 

I would be happy if you could provide this via pull request. Could you please provide also a test and extend the documentation. When you need any help with writing a test, just let me know - i can support you with this.
