### ISSUE TITLE
Basic server example fails if there is no default domain configured in /etc/resolv.conf

### ISSUE THREAD

**Issue by wuftymerguftyguff** [derdanne/puppet-nfs#68]
To recreate:
latest version of module
latest version of all deps
puppet version 4.4.1

manifest:

```
class { '::nfs':
      server_enabled => true,
    }

```
invocation:

`puppet apply nfs.pp`

result:

```
[root@testhost ciu-puppet]# puppet apply nfs.pp
Warning: Undefined variable 'domain';
   (file & line not available)
Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Nfs]: parameter 'nfs_v4_idmap_domain' expects a String value, got Undef at /home/jeffa/nfs.pp:1:1 on node testhost

```

**Comment by derdanne** [comment]
Hi, 

the parameter nfs_v4_idmap_domain should come from your global system environment variable $::domain, as you can see in the params class: https://github.com/derdanne/puppet-nfs/blob/38bf733208d9003b97f0cee16f151f751ad3d31a/manifests/params.pp#L38.

Please check the output on your test system via `facter domain`

**Comment by derdanne** [comment]
I will set a default domain to 'example.com' when no $::domain is defined.

**Comment by derdanne** [comment]
Fixed in https://github.com/derdanne/puppet-nfs/tree/bugfix_rpcbind.service__default_domain

**Comment by wuftymerguftyguff** [comment]
Thanks Daniel,

I am sorry I have not had chance to retest, but your prosed fix will work a treat.

The issue only occurs when the system is poorly configured, but at least it avoids the hard fail.

Thanks again

Jeff

**Comment by derdanne** [comment]
merged to master
