### ISSUE TITLE
Your name causes UTF8 problems :)

### ISSUE THREAD

**Issue by robinbowes** [derdanne/puppet-nfs#7]
It appears that the umlaut character in your name causes problems. Puppet manifests are supposed to be ASCII-only confirmed  in #puppet by _rc (Richard Clamp)

The error looks something like this:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: invalid byte sequence in US-ASCII at /path/to/modules/nfs/manifests/params.pp:1 on node cxpxrbx01pmqs01
```
A work-around is to set ```HTTPD_LANG``` to an UTF8 locale in a relevant place (```/etc/sysconfig/pe-httpd``` in my case as were using PE). eg.
```
HTTPD_LANG=en_GB.UTF8
```

You might like to consider removing the umlaut from your name in puppet manifest files?

**Comment by derdanne** [comment]
Haha,  will solve this with the next release :)

**Comment by derdanne** [comment]
i will fix it within the branch fix_rhel7_issues

**Comment by derdanne** [comment]
merged to master.
