### ISSUE TITLE
rpcbind get re-enabled each time

### ISSUE THREAD

**Issue by pomporov** [derdanne/puppet-nfs#70]
Hi

i have this on each puppet run 

Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind]/enable: enable changed 'false' to 'true'

on ubuntu 16.04
Linux w1 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@www1:~# puppet --version
5.3.3

manifest very simple:

 class { '::nfs':
    client_enabled  => true,
    nfs_v4_client   => true,
  }
  Nfs::Client::Mount <<| |>>

rpcbind installed and running

root@w1:~# dpkg --get-selections |grep rpcbind
rpcbind						install
root@w1:~# ps auxwww|grep rpc
root      6154  0.0  0.1  49676  3392 ?        Ss   Dec03   0:01 /sbin/rpcbind -f -w
root      7365  0.0  0.0      0     0 ?        S<   Dec03   0:00 [rpciod]
statd    12426  0.0  0.1  37416  2852 ?        Ss   Dec04   0:00 /sbin/rpc.statd --no-notify

any ideas ? 
thanks

**Comment by derdanne** [comment]
Hi, thanks for the report. Puppet does not correctly handle the "indirect" status from systemd.

I will work around and set the rpcbind "enable" to "false" and "running" to "true". This should restore idempotence, it is already pushed to develop branch.

**Comment by pomporov** [comment]
cool 
thanks alot

**Comment by derdanne** [comment]
merged to master

**Comment by decibelhertz** [comment]
FWIW, I too have this issue on:
```
# facter -p os
{
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.3 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}
# puppet --version
4.10.8

# uname -a
Linux stsdevu 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Will also note that my CentOS nodes are fine; just the Ubunutu nodes have the issue.

**Comment by derdanne** [comment]
Hi,

we had the same bug for CentOS a couple of weeks ago. It seems to be related to systemd and how puppet treats "indirect" services.

I will prepare a new release in the next days.

Cheers
Daniel

**Comment by derdanne** [comment]
Version 2.0.6 containing the Bugfix is published now

**Comment by decibelhertz** [comment]
Thanks. I've tested it and it resolves the issue for me.
