### ISSUE TITLE
Puppet stuck modifying rpc services on every run with NFS v4 client.

### ISSUE THREAD

**Issue by nvergottini** [derdanne/puppet-nfs#73]
I setup an NFS v4 client using the following basic configuration.
```
class { '::nfs':
  client_enabled      => true,
  nfs_v4_client       => true,
  nfs_v4_idmap_domain => $facts['domain'],
}

Nfs::Client::Mount <<| nfstag == 'utilsrv1' |>>
```
Puppet seems to be stuck permanently making the following correct changes on every run.

Service[rpcbind.service]
enable changed 'true' to 'false'

Service[rpcbind.socket]
enable changed 'false' to 'true'

I'm running Puppet Enterprise 2016.5.2 and my client server is running Oracle Linux 7.4.

**Comment by derdanne** [comment]
Hi,

thanks for reporting this bug. This should be the same bug like described in #70, and could be fixed by splitting the rpcbind service and socket like in https://github.com/derdanne/puppet-nfs/blob/41d1cc694539a0c69fdb3dccf710b26d57e06896/manifests/params.pp#L154. 

I have no experience with Oracle Linux. Which $::osfamily does it use? Would you be able to add the support of Oracle Linux as a pull request?

Best regards,
Daniel

**Comment by nvergottini** [comment]
Oracle Linux 7 is an RHEL 7 clone except that we are using their Unbreakable Linux kernel instead of the Red Hat compatible kernel. The rpcbind.service is also set to indirect, but I'm curious about rpcbind.socket since I'm showing it is enabled, but Puppet keeps saying it is changing enable from false to true.
```
[root@neil-test www]# systemctl is-enabled rpcbind.service
indirect
[root@neil-test www]# systemctl is-enabled rpcbind.socket
enabled
[root@neil-test www]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for neil-test
Info: Applying configuration version '1518702490'
Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind.service]/enable: enable changed 'true' to 'false'
Notice: /Stage[main]/Nfs::Client::Service/Service[rpcbind.socket]/enable: enable changed 'false' to 'true'
Notice: Applied catalog in 5.80 seconds
```

**Comment by derdanne** [comment]
I will need some time to setup a testing environment with Oracle Linux, unfortenately i can't test versus PE.

**Comment by nvergottini** [comment]
I can't imagine Oracle Linux would operate any different vs RHEL in this regard. If there are any changes you would like me to test, I'm open to helping.

**Comment by derdanne** [comment]
Oracle Linux unfortenately does operate differently than RHEL 7, but it could also be PE which behaves differently. When you look at #55, you'll see that we've applied a fix for handling rpcbind.service and rpcbind.socket within RHEL 7 and CentOS 7.

**Comment by nvergottini** [comment]
Which version of Puppet are you testing against? The version of Puppet in PE 2016.5.2 is 4.8.

**Comment by nvergottini** [comment]
Here's what I see in your params.pp for RedHat family.
 ```
         $client_nfsv4_services      = { 'rpcbind.service' => {
                                            ensure => 'running',
                                            enable => false,
                                          },
                                          'rpcbind.socket' => {
                                            ensure => 'running',
                                            enable => true,
                                          },
                                        }
```
Based on that, what I am seeing makes perfect sense. If I manually disable rpcbind.service, it disables rpcbind.socket. So you are effectively disabling and then enabling rpcbind.socket on every run.

I did a little searching and found this.

https://github.com/ghoneycutt/puppet-module-rpcbind/issues/27

This indicates that Puppet 4.9 changed the behavior for indirect services so that enable = false, so that should solve this problem. Since I'm still on Puppet 4.8, it would appear it is time for me to upgrade Puppet.

**Comment by derdanne** [comment]
OK, thanks for investigatting. Can you please report back, if the update to a Puppet version >=4.9 does fix this issue?

**Comment by jurim76** [comment]
Is rpcbind service still needed for NFSv4?

**Comment by derdanne** [comment]
This issue should be fixed with PR #81, can you verify if the latest release also works for you?

**Comment by dgoldsmith** [comment]
I am experiencing the same issue with CentOS 7.4 and Puppet 5.5 (community version).  I will try pulling the PR#81 code to see if that solves the issue for me.

**Comment by derdanne** [comment]
Hi @dgoldsmith, could you approve, this is working for you?

**Comment by dgoldsmith** [comment]
Sorry for the lack of reply.  Yes, using PR #81 solved the issue for me.

**Comment by derdanne** [comment]
Thanks!
