### ISSUE TITLE
Could not find resource 'Augeas[/etc/idmapd.conf]'

### ISSUE THREAD

**Issue by JvGinkel** [derdanne/puppet-nfs#74]
On Puppet 4.10.5 and 5.3.2 with the following parameters I get the message:

`Could not find resource 'Augeas[/etc/idmapd.conf]' in parameter 'subscribe'`

This happens when I call the `nfs` class with the following parameters:
```puppet
class { '::nfs':
  server_enabled         => true,
  client_enabled         => true,
  client_services_enable => true,
  nfs_v4_client          => true,
}
```

**Comment by JvGinkel** [comment]
Create PR #75

**Comment by derdanne** [comment]
PR #75 is merged, i'll plan a new release for the upcoming week.
