### ISSUE TITLE
Unnecessary file resource in mkdir function?

### ISSUE THREAD

**Issue by robinbowes** [derdanne/puppet-nfs#8]
Is the file resource in the mkdir function strictly necessary?

https://github.com/derdanne/puppet-nfs/blob/master/manifests/functions/mkdir.pp#L30-L32

It means it is not possible to set perms on the root of the mounted dir as it causes a duplicate file resource.

**Comment by derdanne** [comment]
Removed the file resource in fix_rhel7_issues

**Comment by derdanne** [comment]
merged to master.
