### ISSUE TITLE
Customize idmapd.conf and other options

### ISSUE THREAD

**Issue by xhejtman** [derdanne/puppet-nfs#87]
Any chance for support to set Local-Realms and Cache-Expiration in /etc/idmapd.conf?
Currently only Domain is supported.
Also customizing GSSDOPTS in defaults config would be appreciated.

**Comment by derdanne** [comment]
Hey @xhejtman,

i would definitely appreciate a pull request for this feature - maybe you can do this?

Best regards,
Daniel

**Comment by xhejtman** [comment]
Sent you an email with patches.

**Comment by derdanne** [comment]
Hi, thanks! I will have a look at it.

**Comment by derdanne** [comment]
I have created the branch https://github.com/derdanne/puppet-nfs/tree/customize_idmapd_and_other_options and applied the patches

**Comment by derdanne** [comment]
Basically this looks good. I have added some small changes:

-> fix some minor syntax errors 
-> set some variables to undef if not set
-> add the new variables in params for all ostypes
-> rename the variable $client_gssd_service to $client_gssd_service_name
-> add the option to enable/disable management of "Nobody" mapping (default disable -> compatibility)

**Comment by xhejtman** [comment]
Thanks, hopefully it arrives soon released. 

Btw, there is a bug in debian 8 in systemd, if you restart rpcbind service, e.g., due to OPTIONS changes, sometimes rpcbind is not running anymore and systemd thinks it is active (but dead). However, service restart does nothing in this case, one has to stop and start the service. Not sure how to workaround this.

**Comment by derdanne** [comment]
Hey, i need to add spec tests and documentation as well before this can be merged.

**Comment by derdanne** [comment]
released in 2.1.0
