### ISSUE TITLE
Debian - Nobody-Group idmapd issue

### ISSUE THREAD

**Issue by jurim76** [derdanne/puppet-nfs#88]
By default Nobody-Group for idmapd service is "nobody" group , but in Debian user nobody belongs to "nogroup" group and service is refused to start under "nobody:nobody". 
If define options in puppet, for example
class { '::nfs':
  client_idmapd_setting => [ 'Nobody-User=nobody', 'Nobody-Group=nogroup' ]
}
and got error
Error: /Stage[main]/Nfs::Client::Config/Augeas[/etc/default/nfs-common]: Could not evaluate: Unknown command Nobody
Notice: /Stage[main]/Nfs::Client/Anchor[nfs::client::end]: Dependency Augeas[/etc/default/nfs-common] has failures: true

**Comment by derdanne** [comment]
Hey, thanks for your report. 

When using client_idmapd_setting, you'll have to use the augeas syntax ("set key value") like:

`$client_idmapd_setting      = ['set NEED_IDMAPD yes']`

--> https://puppet.com/docs/puppet/5.5/resources_augeas.html

**Comment by jurim76** [comment]
This does not work for me, if client uses NFSv4. The module make attempt to write idmapd settings into nfs-common config, which is wrong.

From nfs/manifests/client/config.pp
  if $::nfs::client::nfs_v4 {
    if $::nfs::defaults_file != undef {
      augeas { $::nfs::defaults_file:  <- variable point to /etc/default/nfs-common, not /etc/idmapd.conf
        context => "/files/${::nfs::defaults_file}", 
        changes => $::nfs::client_idmapd_setting,
      }
    }

**Comment by derdanne** [comment]
Hi, this is a valid point, please look at the issue #87, which adresses the same problem.
