### ISSUE TITLE
SELinux Context flipping

### ISSUE THREAD

**Issue by barneycg** [derdanne/puppet-nfs#91]
With an nfsv4 export, if the exported folder has an SElinux context set it gets overridden by the file resource in create_export.
eg
```
Notice: /Stage[main]/Profile::Postgres_cluster/File[/var/lib/pgsql/9.6/pg_archive]/seltype: seltype changed 'usr_t' to 'postgresql_db_t'
Notice: /Stage[main]/Profile::Nfs/Nfs::Server::Export[/var/lib/pgsql/9.6/pg_archive]/Nfs::Functions::Create_export[/export/pg_archive]/File[/export/pg_archive]/seltype: seltype changed 'postgresql_db_t' t
o 'usr_t'
```

I've temporarily fixed by setting  selinux_ignore_defaults to true in that file resource but that is probably too simplistic and needs exposing all the way up ?

**Comment by derdanne** [comment]
Fixed with PR #92 - thanks!
